---
- name: win_file module demo
  hosts: win
  become: false
  gather_facts: false
  vars:
    myfile: 'C:\temp\devopslab\file1.txt'
  tasks:
    - name: Creating an empty file
      ansible.windows.win_file:
        path: "{{ myfile }}"
        state: touch