---
- name: Power on VMs and generate CSV report
  hosts: vcenter_server
  gather_facts: no
  tasks:
    - name: Gather VM facts
      vmware_guest_facts:
        hostname: "{{ inventory_hostname }}"
        username: your_username
        password: your_password
      register: vm_facts

    - name: Power on VMs
      vmware_guest_powerstate:
        hostname: "{{ inventory_hostname }}"
        username: your_username
        password: your_password
        validate_certs: no
        vm_name: "{{ item.guest_name }}"
        state: poweredon
      loop: "{{ vm_facts.instances }}"
      register: poweron_results

    - name: Generate CSV report
      ansible.builtin.template:
        src: vm_report_template.j2
        dest: vm_report.csv

    - name: Display power-on results
      debug:
        var: poweron_results
